[platformio]
src_dir = firmware

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; XIAO ESP32-S3 Sense uses octal PSRAM.
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM

[env:camera]
build_src_filter =
    -<*>
    +<xiao-esp32s3-camera-test/src/>
build_flags =
    ${env.build_flags}
    -Ifirmware/xiao-esp32s3-camera-test/include

